name: Use Reusable Workflow

on:
  push:
  workflow_dispatch:

jobs:

  do-it:
    uses: joel/reusable-workflow/.github/workflows/reusable-workflow.yml@main
    with:
      who-to-greet: "John Doe"

    steps:

      -
        run: echo Hello World
        shell: bash
